### ISSUE TITLE
Colour code more sections in the format line and each line in ass subtitles.

### ISSUE THREAD

**Issue by nathanielcwm** [GalAster/vscode-subtitles#1]
It would be useful to have each section of a subtitle line colour coded with the format.

So for instance the font names could be say red in the format line and it could be red in each style line too.

**Comment by wuyudi** [comment]
The developer is Chinese.So you can speak in Chinese.

**Comment by GalAster** [comment]
Sorry, styles depends on tags is impossible in tmlanguage static highlight.

It needs the dynamic highlight by LSP, which didn't implement by VSC yet.
