### ISSUE TITLE
双语字幕代码显示高亮问题-2020.4.29

### ISSUE THREAD

**Issue by Jagerx** [GalAster/vscode-subtitles#2]
之前用Sublime Text3。其中ASS字幕格式编辑插件用的是
**[Sublime-ASS](https://github.com/jfcherng/Sublime-ASS)**

最近切换VS CODE后发现有Lyrics/Subtitles Support，但是再双语字幕高亮显示方面有些问题。

同一个Ass字幕文件，VS Code和Sublime也是同样的Theme情况下截图如下：

* Sublime Text3：
![2020-04-29_6-35-12](https://user-images.githubusercontent.com/42521386/80545799-c9d6c380-89e6-11ea-9545-d9be160bd4ad.png)

* VS Code
![2020-04-29_6-36-46](https://user-images.githubusercontent.com/42521386/80545715-998f2500-89e6-11ea-93e8-4e1cd45f63b4.png)

**毕竟，双语字幕通常都是中英放在一行，英文部分的格式单独定义，但是Lyrics/Subtitles Support无法像Sublime-ASS一样正常高亮显示行内格式定义代码，以上，感谢！**

**Comment by GalAster** [comment]
这周末准备搞一下支持, 有没有文本样例

**Comment by GalAster** [comment]
现在已经支持了所有的基本指令, 然后 ass 还支持扩展指令.

要添加指令的话改这里, 分别对应数字, 样式, 颜色, 还有函数调用四种类型.

https://github.com/GalAster/vscode-subtitles/blob/0ac07a7ce834cd12899351828d1f2e663a6440e1/syntax/ass.YAML-tmLanguage#L90-L102

还有一种指令比如绘图指令 `\p` 是上下文有关语法, 这个是不可能用静态高亮的所以也就不支持
