### ISSUE TITLE
lrc文件对于3位时间标记显示错误的问题

### ISSUE THREAD

**Issue by xiaosiyu0603** [GalAster/vscode-subtitles#3]
感谢作者dalao的插件，非常有用。不过在使用中发现了一个问题：

在lrc中
```lrc
[00:21.67] La la la la la la la
[00:21.674] La la la la la la la
```
对于第二排毫秒位数为3的格式，会直接判定为错误。
如果能解决这个问题就好了，谢谢大佬！

**Comment by unbadfish** [comment]
![图片](https://user-images.githubusercontent.com/61961263/85218882-234ce480-b3d1-11ea-9ba3-c026d3899970.png)
同上，lrc某一行方括号里只要是[12:34.567]的话那一行就是红色的

> 建议用json文件的方式让用户选择支持两位小数还是三位小数还是都支持

**Comment by GalAster** [comment]
是我疏忽了, 主要是 lrc 我没找到标准

v0.3.3 已修复

**Comment by xiaosiyu0603** [comment]
谢谢😂

**Comment by unbadfish** [comment]
同谢
