### ISSUE TITLE
一个奇怪的BUG

### ISSUE THREAD

**Issue by unbadfish** [GalAster/vscode-subtitles#4]
![截图_2020-08-02_20-45-10](https://user-images.githubusercontent.com/61961263/89136245-44265f00-d565-11ea-9591-7d823f51dfb3.png)
如图所示，这是一个*很奇怪*但是*可复现*的bug

**Comment by Jobsecond** [comment]
好像 `[mm:ss.xx]` 格式的可以，`[mm:ss:xx]` 的不可以。

**Comment by unbadfish** [comment]
谢谢，之前粗心了
这就用正则改
