### ISSUE TITLE
叠句的显示有BUG

### ISSUE THREAD

**Issue by unbadfish** [GalAster/vscode-subtitles#5]
![截图_2020-08-03_09-00-39](https://user-images.githubusercontent.com/61961263/89136799-0bd45000-d568-11ea-935e-1102b18bc587.png)
如图所示……

**Comment by GalAster** [comment]
可能是某种播放器的自定义语法, 并非所有播放器都支持

**Comment by unbadfish** [comment]
但是我所有的MP3和播放器都支持叠句语法
:sob:
